# defaults specify the default config from each component
defaults:

  # dp ref config, inheriting from trainer/config/ref/ref.yaml
  - ref
  
  # fsdp engine config
  - ../engine@fsdp_config: fsdp

  # load the reference default config, then apply the fields in the current yaml
  - _self_

# ref model is assumed to be identical to actor model. Specify model.path for using a different ref model.
# Potential use case involves on policy distillation where we calculate KL divergence between student actor
# and teacher ref
model: null
